name: CI-Deploy Infra-Upload frontend-Upload Functionapp-Test-Deploy

on:
     push:
         branches: [ main ]
         paths:
         - 'frontend/**'
         - 'backend/**'
         - 'infra/**'
         - '.github/workflows/ci-cd.infra.yml'

permissions:
      id-token: write
      contents: read

env:
  FUNCTIONS_DIR: backend
  STATIC_DIR: frontend

jobs:
   # =========================
   # 0) Build Functions ZIP 
   # =========================
  # build_functions:
  #   name: Build Functions zip (Python v2)
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up Python 3.11
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.11'
  #         cache: pip
  #         cache-dependency-path: ${{ env.FUNCTIONS_DIR }}/api/requirements.txt

  #     - name: Vendor deps into .python_packages
  #       working-directory: ${{ env.FUNCTIONS_DIR }}/api
  #       run: |
  #         rm -rf .python_packages
  #         mkdir -p .python_packages/lib/site-packages
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt --target .python_packages/lib/site-packages

  #     - name: Verify required files exist
  #       working-directory: ${{ env.FUNCTIONS_DIR }}/api
  #       run: |
  #         test -f host.json
  #         test -f function_app.py

  #     - name: Create functionapp.zip
  #       run: |
  #         cd "${{ env.FUNCTIONS_DIR }}"
  #         zip -r ../functionapp.zip . \
  #           -x "**/__pycache__/*" ".venv/*" "**/.pytest_cache/*" ".git/*"
  #         ls -lh ../functionapp.zip

  #     - name: Upload artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: functionapp-zip
  #         path: functionapp.zip
  #         if-no-files-found: error

  # =========================
  # 1) Terraform: DEV infra
  # =========================
  infra_build:
    name: Terraform 
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }
    defaults: { run: { working-directory: infra } }
    env:
      TF_IN_AUTOMATION: "1"
      ARM_USE_OIDC: "true" #Create Federated Credentials in Azure
      client-id: ${{ secrets.AZURE_CLIENT_ID }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
      - name: Init state
        run: terraform init -input=false -reconfigure -backend-config="key=cloudchallenge.tfstate"


      - name: Validate
        run: terraform validate

      # Simple tweak: -lock=false on plan to avoid stale lock during planning
      - name: Plan
        run: terraform plan -input=false -lock=false -out=tfplan

      - name: Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -input=false -auto-approve tfplan

      - name: Export DEV outputs
        id: tf_out_dev
        run: |
          echo "rg=$(terraform output -raw rg_name)"                                  >> $GITHUB_OUTPUT
          echo "func_name=$(terraform output -raw function_app_name)"                 >> $GITHUB_OUTPUT
          echo "swb_name=$(terraform output -raw swb_name)"                           >> $GITHUB_OUTPUT
          echo "api=https://$(terraform output -raw function_default_hostname)"       >> $GITHUB_OUTPUT
          echo "site_url=$(terraform output -raw site_url)"                           >> $GITHUB_OUTPUT
    outputs:
      rg:        ${{ steps.tf_out_dev.outputs.rg }}
      func_name: ${{ steps.tf_out_dev.outputs.func_name }}
      swb_name:  ${{ steps.tf_out_dev.outputs.swb_name }}
      api:       ${{ steps.tf_out_dev.outputs.api }}
      site_url:  ${{ steps.tf_out_dev.outputs.site_url }}

  # =========================
  # 2) Deploy  (Functions + Static Web)
  # =========================
  infra_deploy:
    name: Deploy Static webapp & Function api
    runs-on: ubuntu-latest
    needs: [infra_build, build_functions]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    env:
      AZ_RG:        ${{ needs.infra_dev.outputs.rg }}
      AZ_FUNC_NAME: ${{ needs.infra_dev.outputs.func_name }}
      AZ_SWB_NAME:  ${{ needs.infra_dev.outputs.swb_name }}
      API_BASE_URL: ${{ needs.infra_dev.outputs.api }}
      SITE_URL:     ${{ needs.infra_dev.outputs.site_url }}
    outputs:
      api: ${{ steps.dev_out.outputs.api }}
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
        inlineScript: |
            az storage blob upload-batch --account-name "${AZ_SWB_NAME}" --auth-mode key -d '$web' -s frontend/ --overwrite